In [47]:
import pandas as pd
import numpy as np
import sklearn
import pickle

run streamlit
streamlit run d:/STUDY/AAMIIN/HACKTIV8/thunder-talk/streamlit_project/app.py

In [39]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [84]:
min(X[:,3])

0.1

In [85]:
max(X[:,3])

2.5

In [52]:
load_iris().feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [40]:
df = load_iris()
X = df.data
y = df.target
print(df.target_names)

['setosa' 'versicolor' 'virginica']


In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3)

In [42]:
logreg = LogisticRegression(random_state=42, solver='liblinear')
logreg.fit(X_train, y_train)

LogisticRegression(random_state=42, solver='liblinear')

In [43]:
y_train_pred = logreg.predict(X_train)
y_test_pred = logreg.predict(X_test)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [45]:
print(classification_report(y_train, y_train_pred))
print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_train, y_train_pred))
print(confusion_matrix(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      0.89      0.94        37
           2       0.90      1.00      0.95        37

    accuracy                           0.96       105
   macro avg       0.97      0.96      0.96       105
weighted avg       0.97      0.96      0.96       105

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

[[31  0  0]
 [ 0 33  4]
 [ 0  0 37]]
[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [49]:
pickle.dump(logreg, open('classifier.pkl', 'wb'))

In [50]:
X_train[0]

array([5.5, 2.4, 3.7, 1. ])

In [86]:
X_train[0]

array([5.5, 2.4, 3.7, 1. ])

In [89]:
prediction_proba = logreg.predict_proba([[5.5, 2.4, 3.7, 1. ]])

In [91]:
class_name = ['setosa', 'versicolor', 'virginica']

In [93]:
prediction_proba_df = pd.DataFrame(prediction_proba, columns=class_name)
prediction_proba_df

setosa  versicolor  virginica
0  0.057389    0.808613   0.133998